name: Deploy Video Streaming

on:
  push:
    branches: [ main, modular ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Package Lambda functions
      run: |
        cd backend
        zip -r auth.zip modules/auth.py modules/utils.py requirements.txt
        zip -r videos.zip modules/videos.py modules/utils.py requirements.txt
    
    - name: Deploy Lambda Auth
      run: |
        cd backend
        aws lambda update-function-code --function-name video-streaming-auth --zip-file fileb://auth.zip
    
    - name: Deploy Lambda Videos
      run: |
        cd backend
        aws lambda update-function-code --function-name video-streaming-upload --zip-file fileb://videos.zip
    
    - name: Deploy Frontend
      run: |
        cd frontend
        aws s3 sync . s3://video-streaming-sstech-eaddf6a1/ --exclude "*.md" --exclude "*.bat" --delete
    
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id E153IH8TKR1LCM --paths "/*"